---
version: "2.0"

services:
  app:
    image: ubuntu:22.04
    
    env:
      - "my_root_password=1" # root password for ssh connection. 
    
    command:
      - "bash"
      - "-c"
    args:
      # Link at the end of the next line needs to be changed to the location of your start.sh file
      - 'apt-get update ; apt-get upgrade -y ; apt-get install -y  curl ;   curl -s https://raw.githubusercontent.com/PavloDereniuk/Launch-a-website-on-Akash-Network-in-2-minutes/main/start.sh | bash ; 
      sleep infinity'   
    expose:
      - port: 80
        as: 80
        # accept:
        #   - "q.ingress.provider-02.sandbox-01.aksh.pw"  
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true   
profiles:
  compute:
    app:
      resources:
        # Specify the required resources
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          size: 2Gi
         
  placement:
    akash: 
      attributes:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
